# Generated by Django 3.0rc1 on 2019-12-03 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=200)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.BoardList')),
            ],
        ),
        migrations.RemoveField(
            model_name='trellolist',
            name='trello_board',
        ),
        migrations.RenameModel(
            old_name='TrelloBoard',
            new_name='Board',
        ),
        migrations.DeleteModel(
            name='TrelloCard',
        ),
        migrations.DeleteModel(
            name='TrelloList',
        ),
        migrations.AddField(
            model_name='boardlist',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Board'),
        ),
    ]
